"""SMILES for amino acids and cannabinoids (workflow-verified). Auto-generated."""
AMINO_SMILES = {
    'Gly': 'NCC(=O)O',
    'Ala': 'CC(N)C(=O)O',
    'Ser': 'NC(CO)C(=O)O',
    'Pro': 'O=C(O)C1CCCN1',
    'Val': 'CC(C)C(N)C(=O)O',
    'Thr': 'CC(O)C(N)C(=O)O',
    'Cys': 'NC(CS)C(=O)O',
    'Leu': 'CC(C)CC(N)C(=O)O',
    'Ile': 'CCC(C)C(N)C(=O)O',
    'Asn': 'NC(=O)CC(N)C(=O)O',
    'Asp': 'NC(CC(=O)O)C(=O)O',
    'Gln': 'NC(=O)CCC(N)C(=O)O',
    'Glu': 'NC(CCC(=O)O)C(=O)O',
    'Lys': 'NCCCCC(N)C(=O)O',
    'Met': 'CSCCC(N)C(=O)O',
    'His': 'NC(Cc1cnc[nH]1)C(=O)O',
    'Phe': 'NC(Cc1ccccc1)C(=O)O',
    'Arg': 'NC(N)=NCCCC(N)C(=O)O',
    'Tyr': 'NC(Cc1ccc(O)cc1)C(=O)O',
    'Trp': 'NC(Cc1c[nH]c2ccccc12)C(=O)O',
}

CANNABINOID_SMILES = {
    'CBG': {'neutral': 'CCCCCc1cc(O)c(C/C=C(\\C)CCC=C(C)C)c(O)c1', 'acid': 'CCCCCc1cc(O)c(C/C=C(\\C)CCC=C(C)C)c(O)c1C(=O)O'},
    'THC': {'neutral': 'CCCCCc1cc(O)c2c(c1)OC(C)(C)[C@@H]1CCC(C)=C[C@H]21', 'acid': 'CCCCCc1c(C(=O)O)c(O)c2c(c1)OC(C)(C)[C@@H]1CCC(C)=C[C@H]21'},
    'D8THC': {'neutral': 'CCCCCc1cc(O)c2c(c1)OC(C)(C)[C@@H]1CC=C(C)C[C@H]21', 'acid': 'CCCCCc1c(C(=O)O)c(O)c2c(c1)OC(C)(C)[C@@H]1CC=C(C)C[C@H]21'},
    'CBD': {'neutral': 'CCCCCc1cc(O)c(C2C=C(C)CC[C@H]2C(=C)C)c(O)c1', 'acid': 'CCCCCc1cc(O)c(C2C=C(C)CC[C@H]2C(=C)C)c(O)c1C(=O)O'},
    'CBC': {'neutral': 'CCCCCc1cc(O)c2c(c1)OC(C)(CCC=C(C)C)C=C2', 'acid': 'CCCCCc1cc(O)c2c(c1)OC(C)(CCC=C(C)C)C=C2C(=O)O'},
    'CBL': {'neutral': 'CCCCCc1cc(O)c2c(c1)OC1(C)CCC3C(C)(C)C3C21', 'acid': 'CCCCCc1c(C(=O)O)c(O)c2c(c1)OC1(C)CCC3C(C)(C)C3C21'},
    'CBN': {'neutral': 'CCCCCc1cc(O)c2c(c1)OC(C)(C)c1ccc(C)cc1-2', 'acid': 'CCCCCc1c(C(=O)O)c(O)c2c(c1)OC(C)(C)c1ccc(C)cc1-2'},
    'CBGV': {'neutral': 'CCCc1cc(O)c(C/C=C(\\C)CCC=C(C)C)c(O)c1', 'acid': 'CCCc1cc(O)c(C/C=C(\\C)CCC=C(C)C)c(O)c1C(=O)O'},
    'CBDV': {'neutral': 'CCCc1cc(O)c(C2C=C(C)CC[C@H]2C(=C)C)c(O)c1', 'acid': 'CCCc1cc(O)c(C2C=C(C)CC[C@H]2C(=C)C)c(O)c1C(=O)O'},
    'THCV': {'neutral': 'CCCc1cc(O)c2c(c1)OC(C)(C)[C@@H]1CCC(C)=C[C@H]21', 'acid': 'CCCc1c(C(=O)O)c(O)c2c(c1)OC(C)(C)[C@@H]1CCC(C)=C[C@H]21'},
}

# ── Extra simulated-library classes (RDKit-validated SMILES) ──────────────────
# Each maps a display name -> neutral SMILES. The per-class "individual" branch
# (protonation / esterification / oxidation / salt) is DERIVED from these by an
# RDKit transform in extra_classes_sim_test.py, so only the neutral form lives
# here. Compounds that are also canonical amino acids (Glycine, Glutamate,
# Aspartate, Cysteine) intentionally reuse the EXACT AMINO_SMILES string so the
# catalog can de-duplicate them by string and merge the category tags.
NEUROTRANSMITTER_SMILES = {
    "Dopamine":        "NCCc1ccc(O)c(O)c1",
    "Serotonin":       "NCCc1c[nH]c2ccc(O)cc12",
    "Norepinephrine":  "NCC(O)c1ccc(O)c(O)c1",
    "Epinephrine":     "CNCC(O)c1ccc(O)c(O)c1",
    "Histamine":       "NCCc1c[nH]cn1",
    "GABA":            "NCCCC(=O)O",
    "Glutamate":       "NC(CCC(=O)O)C(=O)O",
    "Glycine":         "NCC(=O)O",
    "Aspartate":       "NC(CC(=O)O)C(=O)O",
    "Acetylcholine":   "CC(=O)OCC[N+](C)(C)C",
    "Taurine":         "NCCS(=O)(=O)O",
    "Tyramine":        "NCCc1ccc(O)cc1",
    "Tryptamine":      "NCCc1c[nH]c2ccccc12",
    "Octopamine":      "NCC(O)c1ccc(O)cc1",
    "Phenethylamine":  "NCCc1ccccc1",
    "Melatonin":       "CC(=O)NCCc1c[nH]c2ccc(OC)cc12",
    "L-DOPA":          "NC(Cc1ccc(O)c(O)c1)C(=O)O",
    "5-HTP":           "NC(Cc1c[nH]c2ccc(O)cc12)C(=O)O",
    "Agmatine":        "NCCCCNC(N)=N",
    "Choline":         "OCC[N+](C)(C)C",
}

STEROID_SMILES = {
    "Cholesterol":      "CC(C)CCCC(C)C1CCC2C1(CCC3C2CC=C4C3(CCC(C4)O)C)C",
    "Testosterone":     "CC12CCC3C(C1CCC2O)CCC4=CC(=O)CCC34C",
    "Estradiol":        "CC12CCC3C(C1CCC2O)CCC4=C3C=CC(=C4)O",
    "Estrone":          "CC12CCC3C(C1CCC2=O)CCC4=C3C=CC(=C4)O",
    "Estriol":          "CC12CCC3C(C1CC(C2O)O)CCC4=C3C=CC(=C4)O",
    "Progesterone":     "CC(=O)C1CCC2C1(CCC3C2CCC4=CC(=O)CCC34C)C",
    "Hydrocortisone":   "CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O",
    "Cortisone":        "CC12CCC(=O)C=C1CCC3C2C(=O)CC4(C3CCC4(C(=O)CO)O)C",
    "Corticosterone":   "CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4C(=O)CO)C)O",
    "Aldosterone":      "CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C=O)O",
    "Dexamethasone":    "CC1CC2C3CCC4=CC(=O)C=CC4(C3(C(CC2(C1(C(=O)CO)O)C)O)F)C",
    "Prednisolone":     "CC12CC(C3C(C1CCC2(C(=O)CO)O)CCC4=CC(=O)C=CC34C)O",
    "Pregnenolone":     "CC(=O)C1CCC2C1(CCC3C2CC=C4C3(CCC(C4)O)C)C",
    "DHEA":             "CC12CCC3C(C1CCC2=O)CC=C4C3(CCC(C4)O)C",
    "Androstenedione":  "CC12CCC3C(C1CCC2=O)CCC4=CC(=O)CCC34C",
    "Cholic acid":      "CC(CCC(=O)O)C1CCC2C1(C(CC3C2C(CC4C3(CCC(C4)O)C)O)O)C",
    "Deoxycholic acid": "CC(CCC(=O)O)C1CCC2C1(C(CC3C2CCC4C3(CCC(C4)O)C)O)C",
    "Lithocholic acid": "CC(CCC(=O)O)C1CCC2C1(CCC3C2CCC4C3(CCC(C4)O)C)C",
    "beta-Sitosterol":  "CCC(CCC(C)C1CCC2C1(CCC3C2CC=C4C3(CCC(C4)O)C)C)C(C)C",
    "Stigmasterol":     "CCC(C=CC(C)C1CCC2C1(CCC3C2CC=C4C3(CCC(C4)O)C)C)C(C)C",
}

PEPTIDE_SMILES = {
    "Glutathione (GSH)":   "NC(CCC(=O)NC(CS)C(=O)NCC(=O)O)C(=O)O",
    "Glutathione (GSSG)":  "OC(=O)CNC(=O)C(CSSCC(NC(=O)CCC(N)C(=O)O)C(=O)NCC(=O)O)NC(=O)CCC(N)C(=O)O",
    "Cysteine":            "NC(CS)C(=O)O",
    "Cystine":             "OC(=O)C(N)CSSCC(N)C(=O)O",
    "Carnosine":           "NCCC(=O)NC(Cc1c[nH]cn1)C(=O)O",
    "Glycylglycine":       "NCC(=O)NCC(=O)O",
    "Gly-Gly-Gly":         "NCC(=O)NCC(=O)NCC(=O)O",
    "Aspartame":           "COC(=O)C(Cc1ccccc1)NC(=O)C(N)CC(=O)O",
    "Glycyl-tyrosine":     "NCC(=O)NC(Cc1ccc(O)cc1)C(=O)O",
    "Ala-Gln":             "CC(N)C(=O)NC(CCC(N)=O)C(=O)O",
    "Leu-enkephalin":      "NC(Cc1ccc(O)cc1)C(=O)NCC(=O)NCC(=O)NC(Cc1ccccc1)C(=O)NC(CC(C)C)C(=O)O",
    "Met-enkephalin":      "NC(Cc1ccc(O)cc1)C(=O)NCC(=O)NCC(=O)NC(Cc1ccccc1)C(=O)NC(CCSC)C(=O)O",
    "TRH":                 "O=C1CCC(N1)C(=O)NC(Cc1c[nH]cn1)C(=O)N1CCCC1C(N)=O",
    "Ala-Ala":             "CC(N)C(=O)NC(C)C(=O)O",
    "Gly-Ala":             "NCC(=O)NC(C)C(=O)O",
    "Val-Gly":             "CC(C)C(N)C(=O)NCC(=O)O",
    "Phe-Gly":             "NC(Cc1ccccc1)C(=O)NCC(=O)O",
    "Ser-Gly":             "NC(CO)C(=O)NCC(=O)O",
    "Pro-Gly":             "O=C(NCC(=O)O)C1CCCN1",
    "Lys-Gly":             "NCCCCC(N)C(=O)NCC(=O)O",
}

LIPID_SMILES = {
    "Capric acid (C10:0)":    "CCCCCCCCCC(=O)O",
    "Lauric acid (C12:0)":    "CCCCCCCCCCCC(=O)O",
    "Myristic acid (C14:0)":  "CCCCCCCCCCCCCC(=O)O",
    "Palmitic acid (C16:0)":  "CCCCCCCCCCCCCCCC(=O)O",
    "Stearic acid (C18:0)":   "CCCCCCCCCCCCCCCCCC(=O)O",
    "Arachidic acid (C20:0)": "CCCCCCCCCCCCCCCCCCCC(=O)O",
    "Behenic acid (C22:0)":   "CCCCCCCCCCCCCCCCCCCCCC(=O)O",
    "Palmitoleic (C16:1)":    "CCCCCCC=CCCCCCCCC(=O)O",
    "Oleic acid (C18:1)":     "CCCCCCCCC=CCCCCCCCC(=O)O",
    "Linoleic acid (C18:2)":  "CCCCCC=CCC=CCCCCCCCC(=O)O",
    "a-Linolenic (C18:3)":    "CCC=CCC=CCC=CCCCCCCCC(=O)O",
    "Arachidonic (C20:4)":    "CCCCCC=CCC=CCC=CCC=CCCCC(=O)O",
    "EPA (C20:5)":            "CCC=CCC=CCC=CCC=CCC=CCCCC(=O)O",
    "DHA (C22:6)":            "CCC=CCC=CCC=CCC=CCC=CCC=CCCC(=O)O",
    "Tripalmitin":            "CCCCCCCCCCCCCCCC(=O)OCC(OC(=O)CCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCC",
    "Tristearin":             "CCCCCCCCCCCCCCCCCC(=O)OCC(OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCC",
    "Triolein":               "CCCCCCCCC=CCCCCCCCC(=O)OCC(OC(=O)CCCCCCCCC=CCCCCCCC)COC(=O)CCCCCCCCC=CCCCCCCC",
    "Glyceryl monostearate":  "CCCCCCCCCCCCCCCCCC(=O)OCC(O)CO",
    "Methyl stearate":        "CCCCCCCCCCCCCCCCCC(=O)OC",
    "Methyl oleate":          "CCCCCCCCC=CCCCCCCCC(=O)OC",
}
